Python报错(Anaconda或者PyCharm)： RuntimeError: The current Numpy installation (‘D:\Develop\anaconda\lib\site-packages\numpy\init.py’) fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

报错原因：
 1､使用python3.9和numpy1.19.4时会发生此错误
 2、numpy 1.19.4所有Python版本都无法执行的错误。使用以前的版本来解决该问题（版本问题）

解决办法
 file —》 setting 进入下画面
 
 第二：双击进入对应的包

安装后再次运行即可成功

