python API请求——SSL报错

During handling of the above exception, another exception occurred:

关闭验证：verify=False

req = requests.get(URL, verify=False)

验证结果：无SSL报错

